### ISSUE TITLE
Extend rover wheel classifications

### ISSUE THREAD

**Issue by jakkarth** [Arsonide/FinePrint#1]
In stock, sometimes it makes sense to make rovers using the Small Gear Bay part, which is technically a ModuleLandingGear/ModuleSteering instead of ModuleWheel.

Additionally, many part mods add landing gear/wheels using module FSwheel from the Firespitter mod.

If possible, I'd like to request that ModuleLandingGear and FSwheel be added to the types of parts that rover contracts use for ground checks, so that rovers built using them can complete the exploration contracts.

Thanks for the awesome new contracts!

**Comment by Arsonide** [comment]
I'm doing some research as to how to detect mod parts without creating a hard dependency to the mod. The moment I find out how to do this, I'll do it, but I don't want to create dependencies.

**Comment by Arsonide** [comment]
I have added this suggestion, as well as support for many other mods like RemoteTech 2 and Interstellar.
