### ISSUE TITLE
No part testing contracts

### ISSUE THREAD

**Issue by Kosmolaut** [Arsonide/FinePrint#20]
I have not seen a single vanilla testing contract (except the first hardcoded ones) since I started a fresh Savegame. I declined dozens of satellite-contracts and never got a part tester.

Even stranger: Sometimes the "Start a new Vessel"-contract appears again. Debug-Menu doesn't help.

**Comment by Arsonide** [comment]
I will need more information to diagnose this, preferably the mods you are using, whether you are 64 bit or not, a log, and a save if possible.

Usually this is just a matter of RNG, but it could be some sort of mod conflict. I can't say for sure without more information.

**Comment by Kosmolaut** [comment]
Here are some Screenshots and Logs.
![screenshot21](https://cloud.githubusercontent.com/assets/8673921/4174871/0deb6176-35af-11e4-9b29-d2494320cc73.png)
![screenshot22](https://cloud.githubusercontent.com/assets/8673921/4174872/107b9866-35af-11e4-8ac0-887e78c17dcb.png)

https://www.dropbox.com/s/15nhsts41mzxiq7/output_log.txt?dl=0
https://www.dropbox.com/s/yuwvfcrx7lf7u2j/KSP.log?dl=0

**Comment by Kosmolaut** [comment]
And my Savegame: https://dl.dropboxusercontent.com/u/21106171/quicksave.sfs

**Comment by Arsonide** [comment]
Kerbal Alarm Clock is spamming that log so much that I don't even see Fine Print - or anything else for that matter - loading. Do you think you could remove that temporarily and create another log?

**Comment by Kosmolaut** [comment]
Maybe I uploaded the wrong Log, sorry about the mess. I removed Kerbal Alarm Clock and made a new log, same link: https://dl.dropboxusercontent.com/u/21106171/output_log.txt

I started a new game. But the problems have remained the same.

**Comment by Arsonide** [comment]
I looked over the log and didn't see anything suspicious, the screenshots suggest something awry though. You haven't even launched a vessel yet, but satellite contracts are showing up, meaning you must have boosted your way up the research tree somehow manually.

Part testing contracts usually start showing up after you finish the World First contracts, so I do not think this issue is Fine Print related.
