### ISSUE TITLE
Show/Hide Map Waypoints

### ISSUE THREAD

**Issue by timj11dude** [Arsonide/FinePrint#3]
Might there be a method for showing and hiding the waypoint objectives for contracts? Perhaps with waypoint contracts accepted, only show the waypoints of contracts that are current shown "expanded" in the contract toolbar window. 
Understandably there is utility in checking the waypoints of a yet to be accepted contract, and due to limited availablity of waypoint contracts at any one time this is less of an issue, but this too can feel a little intruisive. Limiting the waypoints of un-accpeted contracts only be shown when viewing the map through the tracking station, could be one such way to reduce intrusiveness.

**Comment by timj11dude** [comment]
Yet to test these issues on version 0.57b. The above is with reference to the 0.54a version.

**Comment by Arsonide** [comment]
I've seen your suggestions, and they are on the list of things to get done, but not until configuration is complete. I have left this issue open as a reminder to myself.

**Comment by Arsonide** [comment]
As of https://github.com/Arsonide/FinePrint/commit/f9420280d8ef3d73f8393d969b27e894655d6b6e this is a thing.
